### ISSUE TITLE
3.0 tag does not match release 3.0

### ISSUE THREAD

**Issue by cboyd10** [johndimopoulos/moodle-gradingform_erubric#2]
It appears that your tag and release do not match. I was hoping that you could fix that so that I could reference your tag for the 3.0 release instead of having to point at master.

Thanks!

**Comment by johndimopoulos** [comment]
Thank you for your input. 

I believe it's OK now. Let me know if there is something else, so that we can close this issue.

Cheers :)

**Comment by cboyd10** [comment]
Yes, it seems to be correct now. Thank you for fixing that! :)
