### ISSUE TITLE
Sum of points for all quiz attempts ?

### ISSUE THREAD

**Issue by miroi** [johndimopoulos/moodle-gradingform_erubric#6]
Hello,

I would like to ask if it is possible to have sum of all points of all quiz attempts per user ?

Thanks.

**Comment by johndimopoulos** [comment]
Hello friend,

At this point this plugin doesn't handle quizzes, only assignments.

Regards...

**Comment by miroi** [comment]
Ah, sorry for bothering ...closing this ticket as irrelevant.
